### ISSUE TITLE
404 - file not found error

### ISSUE THREAD

**Issue by wouter-kremer** [synobsys/mendix-DragAndDropSupportWidget#3]
We use this widget in Mx version 6.5.1. After login we get the following message in the modeller

404 - file not found for file: widgets/DragAndDropSupportWidget/lib/jquery-1.10.2.min.map

Our questions:

1. Is this widget supported in 6.5.1?
a. If yes how to resolve this error?
b. If no, how to remove the widget because when we delete the widget (and every entity etc) after login no page is loaded at all
![2016-06-07 10_36_11-master main line - mendix modeler 6 5 1 - edge](https://cloud.githubusercontent.com/assets/19794624/15851176/f9af1974-2c9b-11e6-89dc-6941ae12469c.png)
![2016-06-07 10_34_30-master main line - mendix modeler 6 5 1 - modeller](https://cloud.githubusercontent.com/assets/19794624/15851175/f9ae69ac-2c9b-11e6-9fe9-eeef94b2a1f8.png)

...?

**Comment by MarcoGroenenberg** [comment]
I will look at it!

**Comment by wouter-kremer** [comment]
Can you please give us an update? We are stucked right now qith a non-working model...

Thanks!

**Comment by MarcoGroenenberg** [comment]
I am busy with the pivottable which is fixed now and I will look into this after.

**Comment by MarcoGroenenberg** [comment]
Hello Wouter,

I upgrade the widget and widget demo to Mendix release 6.5.1

Can you please check if it is ok for you now. (Only in Github for now)

**Comment by wouter-kremer** [comment]
Thank you very much. We will start testing en i will let you now!

**Comment by wouter-kremer** [comment]
i have tried to donwload the new widget for Mendix 6 but where can i find it on github?

**Comment by RCatersels** [comment]
When you look at the test directory it looks like the DragAndDropSupportWidget.mpk is not refreshed. It is still the same file from a year ago.
